name: CI

on:
  push:

permissions:
  contents: read
  packages: write

env:
  GO_VERSION: "1.24.5"
  IMAGE: ghcr.io/cloudwebmanage/cwm-minio-tierer

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - uses: CloudWebManage/cwm-iac/actions/docker-build-push@main
        with:
          test_script: make validate
          image_suffix: cwm-minio-tierer
          deploy_key_b64: ${{ secrets.CWM_WORKER_CLUSTER_DEPLOY_KEY_B64 }}
          deploy_file_path: config/auto-updated/cwm-minio-tierer/tierer.yaml
          deploy_content_template: |
            cwmMinioTierer:
              tierer:
                image: "__IMAGE__"
          deploy_commit_message: "Update cwm-minio-tierer/tierer"
